Library DEPI/Controllers/BooksController.cs
using Library_DEPI.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace Library_DEPI.Controllers
{
    public class BooksController : Controller
    {
        private readonly IBookServices _bookservices;
        private readonly IAuthorServices _authorservices;
        private readonly IGenreServices _genreservices;
        private readonly ICheckoutServices _checkoutservices;
        private readonly UserManager<IdentityUser> _usermanager;

        public BooksController(IBookServices bookservices, IAuthorServices authorservices, IGenreServices genreservices, ICheckoutServices checkoutServices, UserManager<IdentityUser> usermanager)
        {
            _bookservices = bookservices;
            _authorservices = authorservices;
            _genreservices = genreservices;
            _checkoutservices = checkoutServices;
            _usermanager = usermanager;
        }

        // GET: Books
        public async Task<IActionResult> Index(string searchString, string searchBy)
        {
            var books = _bookservices.GetAll(); 

            if (!string.IsNullOrEmpty(searchString))
            {
                switch (searchBy)
                {
                    case "Title":
                        books = books.Where(b => b.Title.Contains(searchString));
                        break;
                    case "Author":
                        books = books.Where(b => b.Author.Name.Contains(searchString));
                        break;
                    case "Genre":
                        books = books.Where(b => b.Genre.Name.Contains(searchString));
                        break;
                }
            }

            var result = await books.ToListAsync();

            return View(result);
        }


        // GET: Books/Details/5
        public async Task<IActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = _bookservices.GetOne(id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        [Authorize(Roles = $"{MyRoles.SuperAdminRole},{MyRoles.AdminRole}")]

        // GET: Books/Create
        public IActionResult Create()
        {
            ViewBag.Authors = _authorservices.GetAll();
            ViewBag.Genres= _genreservices.GetAll();
            return View();
        }


        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create(BookViewModel bookVM)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        string fileName = string.Empty;
        //        if (bookVM.Image != null)
        //        {
        //            string myFilePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images");
        //            if (!Directory.Exists(myFilePath))
        //                Directory.CreateDirectory(myFilePath);
        //            fileName = Guid.NewGuid().ToString() + Path.GetExtension(bookVM.Image.FileName);
        //            string fullPath = Path.Combine(myFilePath, fileName);
        //            bookVM.Image.CopyTo(new FileStream(fullPath, FileMode.Create));
        //            bookVM.BookImagePath = fileName;
        //        }
        //        else
        //        {
        //            bookVM.BookImagePath = "default.png";
        //            //fileName = "default.png";
        //        }
        //        var book = new Book
        //        {
        //            Title =bookVM.Title,
        //            Description =bookVM.Description,
        //            AvailabilityStatus =bookVM.AvailabilityStatus,
        //            PublishedDate =bookVM.PublishedDate,
        //            AuthorID =bookVM.AuthorID,
        //            GenreID =bookVM.GenreID,
        //            BookImage= $"{bookVM.BookImagePath}",


        //            //BookImage = $"{bookVM.BookImagePath}",
        //        };
        //        if (_bookservices.create(book))
        //        {

        //            return RedirectToAction(nameof(Index));
        //        }

        //        ViewBag.Authors = _authorservices.SelectedItems();
        //        ViewBag.Genres = _genreservices.SelectedItems();
        //        return View(bookVM);


        //    }
        //    ViewBag.Authors = _authorservices.SelectedItems();
        //    ViewBag.Genres = _genreservices.SelectedItems();
        //    return View(bookVM);

        //}



        [Authorize(Roles = $"{MyRoles.SuperAdminRole},{MyRoles.AdminRole}")]

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BookViewModel bookVM)
        {
                if (_bookservices.BookExists(bookVM.Title, bookVM.AuthorID, bookVM.GenreID))
                {
                    ModelState.AddModelError("", "This book already exists with the same details.");
                    //ViewBag.Authors = _authorservices.GetAll();
                    //ViewBag.Genres = _genreservices.GetAll();
                    //return View(bookVM);
                }
            if (ModelState.IsValid)
            {

                string fileName = "default.png"; 

                if (bookVM.Image != null)
                {
                    try
                    {
                        string myFilePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images");
                        if (!Directory.Exists(myFilePath))
                            Directory.CreateDirectory(myFilePath);

                        fileName = Guid.NewGuid().ToString() + Path.GetExtension(bookVM.Image.FileName);
                        string fullPath = Path.Combine(myFilePath, fileName);
                        using (var stream = new FileStream(fullPath, FileMode.Create))
                        {
                            await bookVM.Image.CopyToAsync(stream);
                        }
                    }
                    catch (Exception ex)
                    {
                        ModelState.AddModelError("", "فشل رفع الصورة. حاول مرة أخرى.");
                    }
                }

                var book = new Models.Book
                {
                    Title = bookVM.Title,
                    Description = bookVM.Description,
                    AvailabilityStatus = bookVM.AvailabilityStatus,
                    PublishedDate = bookVM.PublishedDate,
                    AuthorID = bookVM.AuthorID,
                    GenreID = bookVM.GenreID,
                    BookImage = fileName
                };


                

                if (_bookservices.create(book))
                {
                    return RedirectToAction(nameof(Index));
                }

            }

            var errors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage);
            foreach (var error in errors)
            {
                Console.WriteLine(error); 
            }

            ViewBag.Authors = _authorservices.GetAll();
            ViewBag.Genres = _genreservices.GetAll();
            return View(bookVM);
        }



        [Authorize(Roles = $"{MyRoles.SuperAdminRole},{MyRoles.AdminRole}")]
           //GET : Books/Edit/5 
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = _bookservices.GetOne(id);
            if (book == null)
            {
                return NotFound();
            }
            var bookVM = new BookViewModel
            {
                Title = book.Title,
                Description = book.Description,
                AvailabilityStatus = book.AvailabilityStatus,
                PublishedDate = book.PublishedDate,
                AuthorID = book.AuthorID,
                GenreID = book.GenreID,
                BookImagePath = book.BookImage,

                // If you want to pass the image path, consider adding it here
                // bookImagePath = book.bookImagePath // If applicable
            };
            ViewBag.Authors = _authorservices.GetAll();
            ViewBag.Genres = _genreservices.GetAll();
            return View(bookVM);
        }



        [Authorize(Roles = $"{MyRoles.SuperAdminRole},{MyRoles.AdminRole}")]

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, BookViewModel bookVM)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (_bookservices.BookExists(bookVM.Title, bookVM.AuthorID, bookVM.GenreID, id))
            {
                ModelState.AddModelError("", "This book already exists with the same details.");
                //ViewBag.Authors = _authorservices.GetAll();
                //ViewBag.Genres = _genreservices.GetAll();
                //return View(bookVM);
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var book = _bookservices.GetOne(id);
                    if (book == null)
                    {
                        return NotFound();
                    }

                    // Check if the book is currently checked out
                    var checkout = await _checkoutservices.GetActiveCheckoutForBook(id);
                    if (checkout != null && bookVM.AvailabilityStatus)
                    {

Library DEPI/Controllers/GenresController.cs
using Microsoft.AspNetCore.Authorization;

namespace Library_DEPI.Controllers
{
    public class GenresController : Controller
    {
        private readonly IGenreServices _genreServices;

        public GenresController(IGenreServices genreServices)
        {
            _genreServices = genreServices;
        }

        // GET: Genres
        public async Task<IActionResult> Index()
        {
            return View(_genreServices.GetAll());
        }

        // GET: Genres/Details/5
        public async Task<IActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genre = _genreServices.GetOne(id);
            if (genre == null)
            {
                return NotFound();
            }

            return View(genre);
        }

        [Authorize(Roles = $"{MyRoles.SuperAdminRole},{MyRoles.AdminRole}")]
        // GET: Genres/Create
        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = $"{MyRoles.SuperAdminRole},{MyRoles.AdminRole}")]
        // POST: Genres/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Genre genre)
        {
            if (_genreServices.ExistsByName(genre.Name)) 
            {
                ModelState.AddModelError("Name", "This genre name already exists. Please choose a different name.");
            }

            if (ModelState.IsValid)
            {
                _genreServices.create(genre);
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        [Authorize(Roles = $"{MyRoles.SuperAdminRole},{MyRoles.AdminRole}")]
        // GET: Genres/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genre = _genreServices.GetOne(id);
            if (genre == null)
            {
                return NotFound();
            }
            return View(genre);
        }

        [Authorize(Roles = $"{MyRoles.SuperAdminRole},{MyRoles.AdminRole}")]
        // POST: Genres/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Genre genre)
        {
            if (id != genre.Id)
            {
                return NotFound();
            }

            if (_genreServices.ExistsByName(genre.Name, id)) 
            {
                ModelState.AddModelError("Name", "This genre name already exists. Please choose a different name.");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _genreServices.Update(id, genre);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_genreServices.IsExist(genre.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        [Authorize(Roles = $"{MyRoles.SuperAdminRole},{MyRoles.AdminRole}")]
        // GET: Genres/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genre = _genreServices.GetOne(id);
            if (genre == null)
            {
                return NotFound();
            }

            return View(genre);
        }

        [Authorize(Roles = $"{MyRoles.SuperAdminRole},{MyRoles.AdminRole}")]
        // POST: Genres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var genre = _genreServices.GetOne(id);
            if (genre != null)
            {
                _genreServices.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        
    }
}

Library DEPI/Controllers/RolesController.cs
using Microsoft.AspNetCore.Authorization;
using Newtonsoft.Json;

namespace Library_DEPI.Controllers
{
    [Authorize(Roles = $"{MyRoles.SuperAdminRole}")]

    
    public class RolesController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public RolesController(UserManager<IdentityUser> userManager, RoleManager<IdentityRole> RoleManagr)
        {
            _userManager = userManager;
            _roleManager = RoleManagr;
        }
        public async Task<IActionResult> Index()
        {
            var users = await _userManager.Users.ToListAsync();
            return View(users);
        }
        public async Task<IActionResult> addRoles(string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);
            var userRoles = await _userManager.GetRolesAsync(user);

            var allRoles = await _roleManager.Roles.ToListAsync();
            if (allRoles != null)
            {
                var roleList = allRoles.Select(r => new roleViewModel()
                {
                    roleId = r.Id,
                    roleName = r.Name,
                    useRole = userRoles.Any(x => x == r.Name)
                });
                ViewBag.userName = user.UserName;
                ViewBag.userId = userId;
                return View(roleList);
            }
            else
                return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> addRoles(string userId, string jsonRoles)
        {
            var user = await _userManager.FindByIdAsync(userId);

            List<roleViewModel> myRoles =
                JsonConvert.DeserializeObject<List<roleViewModel>>(jsonRoles);

            if (user != null)
            {
                var userRoles = await _userManager.GetRolesAsync(user);

                foreach (var role in myRoles)
                {
                    if (userRoles.Any(x => x == role.roleName.Trim()) && !role.useRole)
                    {
                        await _userManager.RemoveFromRoleAsync(user, role.roleName.Trim());
                    }

                    if (!userRoles.Any(x => x == role.roleName.Trim()) && role.useRole)
                    {
                        await _userManager.AddToRoleAsync(user, role.roleName.Trim());
                    }
                }

                return RedirectToAction(nameof(Index));
            }
            else
                return NotFound();
        }
    }
}

Library DEPI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Library_DEPI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Library_DEPI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Library_DEPI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Library_DEPI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Library DEPI/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>DEPI</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="~/assets/bookstack.ico" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/assets/css/styles.css" rel="stylesheet" />
</head>
<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container px-4 px-lg-5">

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    <li class="nav-item"><a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Index">Home</a></li>
                    @* <li class="nav-item"><a class="nav-link" asp-controller="Home" asp-action="Privacy">About</a></li> *@
                    <li class="nav-item"><a class="nav-link" asp-controller="Authors" asp-action="index">Author</a></li>
                    <li class="nav-item"><a class="nav-link" asp-controller="Genres" asp-action="index">Genre</a></li>
                    <li class="nav-item"><a class="nav-link" asp-controller="Books" asp-action="index">Books</a></li>
                    <li class="nav-item"><a class="nav-link" asp-controller="Checkout" asp-action="index">Checkout</a></li>
                    <li class="nav-item"><a class="nav-link" asp-controller="Penalty" asp-action="index">Penalty</a></li>
                    @if(User.IsInRole("Super Admin"))
                    {
                        <li class="nav-item"><a class="nav-link" asp-controller="Roles" asp-action="index">User Roles</a></li>

                    }

                    @* <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="#!">All Products</a></li>
                            <li><hr class="dropdown-divider" /></li>
                            <li><a class="dropdown-item" href="#!">Popular Items</a></li>
                            <li><a class="dropdown-item" href="#!">New Arrivals</a></li>
                        </ul>
                    </li> *@
                   
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>
    <!-- Header-->
    @* <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">Shop in style</h1>
                <p class="lead fw-normal text-white-50 mb-0">With this shop hompeage template</p>
            </div>
        </div>
    </header> *@


    <header class="bg-dark py-5" style="background-image: url('~/wwwroot/assets/images/books-re.jpg'); background-size: cover; background-position: center; position: relative;">
        <div class="overlay" style="background-color: rgba(0, 0, 0, 0.6); position: absolute; top: 0; left: 0; right: 0; bottom: 0;"></div>
        <div class="container px-4 px-lg-5 my-5 position-relative">
            <div class="text-center text-white position-relative" style="z-index: 1;">
                <h1 class="display-4 fw-bolder">Read to Succeed</h1>
                <p class="lead fw-normal text-white-50 mb-0">"Books are a uniquely portable magic."</p>
            </div>
        </div>
    </header>
   


    <!-- Section-->
    <section class="py-5">
        <!-- add body -->
        <div class="align-content-center"> @RenderBody()</div>
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">

                
                
               
@* 
                <div class="col mb-5">
                    <div class="card h-100">
                        <!-- Product image-->
                        <img class="card-img-top" src="~/assets/images/book.jpg" alt="..." />
                        <!-- Product details-->
                        <div class="card-body p-4">
                            <div class="text-center">
                                <!-- Product name-->
                                <h5 class="fw-bolder">Fancy Product</h5>
                                <!-- Product price-->
                                $40.00 - $80.00
                            </div>
                        </div>
                        <!-- Product actions-->
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">View options</a></div>
                        </div>
                    </div>
                </div>
                <div class="col mb-5">
                    <div class="card h-100">
                        <!-- Sale badge-->
                        <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
                        <!-- Product image-->
                        <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
                        <!-- Product details-->
                        <div class="card-body p-4">
                            <div class="text-center">
                                <!-- Product name-->
                                <h5 class="fw-bolder">Special Item</h5>
                                <!-- Product reviews-->
                                <div class="d-flex justify-content-center small text-warning mb-2">
                                    <div class="bi-star-fill"></div>
                                    <div class="bi-star-fill"></div>
                                    <div class="bi-star-fill"></div>
                                    <div class="bi-star-fill"></div>
                                    <div class="bi-star-fill"></div>
                                </div>
                                <!-- Product price-->
                                <span class="text-muted text-decoration-line-through">$20.00</span>
                                $18.00
                            </div>
                        </div>
                        <!-- Product actions-->
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">Add to cart</a></div>
                        </div>
                    </div>
                </div>
                <div class="col mb-5">
                    <div class="card h-100">
                        <!-- Sale badge-->
                        <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
                        <!-- Product image-->
                        <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
                        <!-- Product details-->
                        <div class="card-body p-4">
                            <div class="text-center">
                                <!-- Product name-->
                                <h5 class="fw-bolder">Sale Item</h5>
                                <!-- Product price-->
                                <span class="text-muted text-decoration-line-through">$50.00</span>
                                $25.00
                            </div>
                        </div>
                        <!-- Product actions-->
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">Add to cart</a></div>
                        </div>
                    </div>
                </div>
                <div class="col mb-5">
                    <div class="card h-100">
                        <!-- Product image-->
                        <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
                        <!-- Product details-->
                        <div class="card-body p-4">
                            <div class="text-center">
                                <!-- Product name-->
                                <h5 class="fw-bolder">Popular Item</h5>
                                <!-- Product reviews-->
                                <div class="d-flex justify-content-center small text-warning mb-2">
                                    <div class="bi-star-fill"></div>
                                    <div class="bi-star-fill"></div>
                                    <div class="bi-star-fill"></div>
                                    <div class="bi-star-fill"></div>
                                    <div class="bi-star-fill"></div>
                                </div>
                                <!-- Product price-->
                                $40.00
                            </div>
                        </div>
                        <!-- Product actions-->
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">Add to cart</a></div>
                        </div>
                    </div>
                </div> *@


            </div>
        </div>
    </section>
    <!-- Footer-->
    <footer class="py-5 bg-dark">
        <div class="container"><p class="m-0 text-center text-white">Copyright &copy; DEPI 2024</p></div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="~/assets/js/scripts.js"></script>
</body>
</html>