Library DEPI/Models/Book.cs
namespace Library_DEPI.Models
{
    public class Book
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool AvailabilityStatus { get; set; }
        public DateTime PublishedDate { get; set; }
        public string BookImage { get; set; }
        public int AuthorID { get; set; }
        public Author Author { get; set; }
        public int GenreID { get; set; }
        public Genre Genre { get; set; }

    }
}

Library DEPI/ViewModels/BookViewModel.cs
namespace Library_DEPI.ViewModels
{
    public class BookViewModel
    {
        public string Title { get; set; }
        public string Description { get; set; }
        public bool AvailabilityStatus { get; set; }
        public DateTime PublishedDate { get; set; }
        public string? BookImagePath { get; set; }
        [NotMapped]
        public IFormFile Image { get; set; }
        public int AuthorID { get; set; }
        //public Author Author { get; set; }
        public int GenreID { get; set; }
        //public Genre Genre { get; set; }



       
    }
}

Library DEPI/Controllers/BooksController.cs
using Library_DEPI.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace Library_DEPI.Controllers
{
    public class BooksController : Controller
    {
        private readonly IBookServices _bookservices;
        private readonly IAuthorServices _authorservices;
        private readonly IGenreServices _genreservices;
        private readonly ICheckoutServices _checkoutservices;
        private readonly UserManager<IdentityUser> _usermanager;

        public BooksController(IBookServices bookservices, IAuthorServices authorservices, IGenreServices genreservices, ICheckoutServices checkoutServices, UserManager<IdentityUser> usermanager)
        {
            _bookservices = bookservices;
            _authorservices = authorservices;
            _genreservices = genreservices;
            _checkoutservices = checkoutServices;
            _usermanager = usermanager;
        }

        // GET: Books
        public async Task<IActionResult> Index(string searchString, string searchBy)
        {
            var books = _bookservices.GetAll(); 

            if (!string.IsNullOrEmpty(searchString))
            {
                switch (searchBy)
                {
                    case "Title":
                        books = books.Where(b => b.Title.Contains(searchString));
                        break;
                    case "Author":
                        books = books.Where(b => b.Author.Name.Contains(searchString));
                        break;
                    case "Genre":
                        books = books.Where(b => b.Genre.Name.Contains(searchString));
                        break;
                }
            }

            var result = await books.ToListAsync();

            return View(result);
        }


        // GET: Books/Details/5
        public async Task<IActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = _bookservices.GetOne(id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        [Authorize(Roles = $"{MyRoles.SuperAdminRole},{MyRoles.AdminRole}")]

        // GET: Books/Create
        public IActionResult Create()
        {
            ViewBag.Authors = _authorservices.GetAll();
            ViewBag.Genres= _genreservices.GetAll();
            return View();
        }


        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create(BookViewModel bookVM)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        string fileName = string.Empty;
        //        if (bookVM.Image != null)
        //        {
        //            string myFilePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images");
        //            if (!Directory.Exists(myFilePath))
        //                Directory.CreateDirectory(myFilePath);
        //            fileName = Guid.NewGuid().ToString() + Path.GetExtension(bookVM.Image.FileName);
        //            string fullPath = Path.Combine(myFilePath, fileName);
        //            bookVM.Image.CopyTo(new FileStream(fullPath, FileMode.Create));
        //            bookVM.BookImagePath = fileName;
        //        }
        //        else
        //        {
        //            bookVM.BookImagePath = "default.png";
        //            //fileName = "default.png";
        //        }
        //        var book = new Book
        //        {
        //            Title =bookVM.Title,
        //            Description =bookVM.Description,
        //            AvailabilityStatus =bookVM.AvailabilityStatus,
        //            PublishedDate =bookVM.PublishedDate,
        //            AuthorID =bookVM.AuthorID,
        //            GenreID =bookVM.GenreID,
        //            BookImage= $"{bookVM.BookImagePath}",


        //            //BookImage = $"{bookVM.BookImagePath}",
        //        };
        //        if (_bookservices.create(book))
        //        {

        //            return RedirectToAction(nameof(Index));
        //        }

        //        ViewBag.Authors = _authorservices.SelectedItems();
        //        ViewBag.Genres = _genreservices.SelectedItems();
        //        return View(bookVM);


        //    }
        //    ViewBag.Authors = _authorservices.SelectedItems();
        //    ViewBag.Genres = _genreservices.SelectedItems();
        //    return View(bookVM);

        //}



        [Authorize(Roles = $"{MyRoles.SuperAdminRole},{MyRoles.AdminRole}")]

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BookViewModel bookVM)
        {
                if (_bookservices.BookExists(bookVM.Title, bookVM.AuthorID, bookVM.GenreID))
                {
                    ModelState.AddModelError("", "This book already exists with the same details.");
                    //ViewBag.Authors = _authorservices.GetAll();
                    //ViewBag.Genres = _genreservices.GetAll();
                    //return View(bookVM);
                }
            if (ModelState.IsValid)
            {

                string fileName = "default.png"; 

                if (bookVM.Image != null)
                {
                    try
                    {
                        string myFilePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images");
                        if (!Directory.Exists(myFilePath))
                            Directory.CreateDirectory(myFilePath);

                        fileName = Guid.NewGuid().ToString() + Path.GetExtension(bookVM.Image.FileName);
                        string fullPath = Path.Combine(myFilePath, fileName);
                        using (var stream = new FileStream(fullPath, FileMode.Create))
                        {
                            await bookVM.Image.CopyToAsync(stream);
                        }
                    }
                    catch (Exception ex)
                    {
                        ModelState.AddModelError("", "فشل رفع الصورة. حاول مرة أخرى.");
                    }
                }

                var book = new Models.Book
                {
                    Title = bookVM.Title,
                    Description = bookVM.Description,
                    AvailabilityStatus = bookVM.AvailabilityStatus,
                    PublishedDate = bookVM.PublishedDate,
                    AuthorID = bookVM.AuthorID,
                    GenreID = bookVM.GenreID,
                    BookImage = fileName
                };


                

                if (_bookservices.create(book))
                {
                    return RedirectToAction(nameof(Index));
                }

            }

            var errors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage);
            foreach (var error in errors)
            {
                Console.WriteLine(error); 
            }

            ViewBag.Authors = _authorservices.GetAll();
            ViewBag.Genres = _genreservices.GetAll();
            return View(bookVM);
        }



        [Authorize(Roles = $"{MyRoles.SuperAdminRole},{MyRoles.AdminRole}")]
           //GET : Books/Edit/5 
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = _bookservices.GetOne(id);
            if (book == null)
            {
                return NotFound();
            }
            var bookVM = new BookViewModel
            {
                Title = book.Title,
                Description = book.Description,
                AvailabilityStatus = book.AvailabilityStatus,
                PublishedDate = book.PublishedDate,
                AuthorID = book.AuthorID,
                GenreID = book.GenreID,
                BookImagePath = book.BookImage,

                // If you want to pass the image path, consider adding it here
                // bookImagePath = book.bookImagePath // If applicable
            };
            ViewBag.Authors = _authorservices.GetAll();
            ViewBag.Genres = _genreservices.GetAll();
            return View(bookVM);
        }



        [Authorize(Roles = $"{MyRoles.SuperAdminRole},{MyRoles.AdminRole}")]

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, BookViewModel bookVM)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (_bookservices.BookExists(bookVM.Title, bookVM.AuthorID, bookVM.GenreID, id))
            {
                ModelState.AddModelError("", "This book already exists with the same details.");
                //ViewBag.Authors = _authorservices.GetAll();
                //ViewBag.Genres = _genreservices.GetAll();
                //return View(bookVM);
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var book = _bookservices.GetOne(id);
                    if (book == null)
                    {
                        return NotFound();
                    }

                    // Check if the book is currently checked out
                    var checkout = await _checkoutservices.GetActiveCheckoutForBook(id);
                    if (checkout != null && bookVM.AvailabilityStatus)
                    {

Library DEPI/Controllers/CheckoutController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace Library_DEPI.Controllers
{
    public class CheckoutController : Controller
    {
        private readonly ICheckoutServices _checkoutService;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IBookServices _bookService;
        private readonly AppDBContext _context;

        public CheckoutController(ICheckoutServices checkoutService, UserManager<IdentityUser> userManager, IBookServices bookService, AppDBContext context)
        {
            _checkoutService = checkoutService;
            _userManager = userManager;
            _bookService = bookService;
            _context = context;
        }

       
            public async Task<IActionResult> Index()
            {
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

                if (string.IsNullOrEmpty(userId))
                {
                     return Redirect("/Identity/Account/Register");
                 }

                var checkouts = await _checkoutService.GetAllCheckoutsAsync(userId);
                return View(checkouts);
            }


            public async Task<IActionResult> Details(int id)
        {
            var checkout = await _checkoutService.GetCheckoutByIdAsync(id);
            if (checkout == null)
            {
                return NotFound();
            }

            return View(checkout);
        }

        public async Task<IActionResult> Create(int selectedBookId)
        {
            var viewModel = new CheckoutViewModel
            {
                SelectedBookId = selectedBookId,
                CheckoutDate = DateTime.Now,
                AvailableBooks = await _bookService.GetAll().Where(b=>b.AvailabilityStatus).ToListAsync()
            };

            if (User.IsInRole("Admin") || User.IsInRole("Super Admin"))
            {
                viewModel.AvailableUsers = await _userManager.Users.ToListAsync();
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                viewModel.SelectedUserId = userId;
            }
            else
            {
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                viewModel.SelectedUserId = userId;
            }

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CheckoutViewModel model)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return Redirect("/Identity/Account/Login");
            }

                
            if (ModelState.IsValid)
            {
                await _checkoutService.CreateCheckoutAsync(model);
                return RedirectToAction(nameof(Index));
            }

            model.AvailableBooks = await _bookService.GetAll().Where(b => b.AvailabilityStatus).ToListAsync();

            if (User.IsInRole("Admin") || User.IsInRole("Super Admin"))
            {
                model.AvailableUsers = await _userManager.Users.ToListAsync();
            }

            return View(model);
        }

        [Authorize(Roles = $"{MyRoles.SuperAdminRole},{MyRoles.AdminRole}")]
        public async Task<IActionResult> Edit(int id)
        {
            var checkout = await _checkoutService.GetCheckoutByIdAsync(id);
            if (checkout == null)
            {
                return NotFound();
            }

            var viewModel = new CheckoutViewModel
            {
                Id = checkout.Id,
                CheckoutDate = checkout.CheckoutDate,
                SelectedBookId = checkout.BookID,
                SelectedUserId = checkout.UserId,
                AvailableBooks = await _bookService.GetAll().Where(b => b.AvailabilityStatus || b.Id == checkout.BookID).ToListAsync(),
            };

            if (User.IsInRole("Admin") || User.IsInRole("Super Admin"))
            {
                viewModel.AvailableUsers = await _userManager.Users.ToListAsync();
            }
            else
            {
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                viewModel.SelectedUserId = userId;
            }

            return View(viewModel);
        }




        [Authorize(Roles = $"{MyRoles.SuperAdminRole},{MyRoles.AdminRole}")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, CheckoutViewModel model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _checkoutService.UpdateCheckoutAsync(id, model);
                return RedirectToAction(nameof(Index));
            }

            model.AvailableBooks = await _bookService.GetAll().Where(b => b.AvailabilityStatus || b.Id == model.SelectedBookId).ToListAsync();

            if (User.IsInRole("Admin") || User.IsInRole("Super Admin"))
            {
                model.AvailableUsers = await _userManager.Users.ToListAsync();
            }

            return View(model);
        }

        [Authorize(Roles = $"{MyRoles.SuperAdminRole},{MyRoles.AdminRole}")]
        public async Task<IActionResult> Delete(int id)
        {
            var checkout = await _checkoutService.GetCheckoutByIdAsync(id);
            if (checkout == null)
            {
                return NotFound();
            }

            return View(checkout);
        }


        [Authorize(Roles = $"{MyRoles.SuperAdminRole},{MyRoles.AdminRole}")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _checkoutService.DeleteCheckoutAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Library DEPI/Views/Books/Create.cshtml
@model Library_DEPI.ViewModels.BookViewModel

@{
    ViewData["Title"] = "Create";
}

<h1 class="text-center">Create Book</h1>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card shadow-lg p-4">
                <form asp-action="Create" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group row">
                        <label asp-for="Title" class="control-label col-md-3"></label>
                        <div class="col-md-9">
                            <input asp-for="Title" class="form-control" />
                            <span asp-validation-for="Title" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label asp-for="Description" class="control-label col-md-3"></label>
                        <div class="col-md-9">
                            <input asp-for="Description" class="form-control" />
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="form-group row form-check">
                        <div class="col-md-3"></div>
                        <div class="col-md-9">
                            <label class="form-check-label">
                                <input class="form-check-input" asp-for="AvailabilityStatus" /> Availability Status  @* @Html.DisplayNameFor(model => model.AvailabilityStatus) *@
                            </label>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label asp-for="PublishedDate" class="control-label col-md-3">Published Date</label>
                        <div class="col-md-9">
                            <input asp-for="PublishedDate" class="form-control" />
                            <span asp-validation-for="PublishedDate" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label asp-for="Image" class="control-label col-md-3"></label>
                        <div class="col-md-6">
                            <input type="file" onchange="load(event)" asp-for="Image" class="form-control" />
                            <span asp-validation-for="Image" class="text-danger"></span>
                        </div>
                        <div class="col-md-3">
                            <img id="image" height="100" width="100" style="display:none;" />
                        </div>
                    </div>

                    <div class="form-group row">
                        <label asp-for="AuthorID" class="control-label col-md-3">Author</label>
                        <div class="col-md-9">
                            <select asp-for="AuthorID" class="form-control" asp-items="@(new SelectList(ViewBag.Authors, "Id", "Name"))"></select>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label asp-for="GenreID" class="control-label col-md-3">Genre</label>
                        <div class="col-md-9">
                            <select asp-for="GenreID" class="form-control" asp-items="@(new SelectList(ViewBag.Genres, "Id", "Name"))"></select>
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-3"></div>
                        <div class="col-md-9">
                            <input type="submit" value="Create" class="btn btn-primary" style="font-size:20px;" />
                        </div>

                        <div>
                            <a asp-action="Index" class="btn btn-secondary " style="float:right;">Back to List</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


<script>
    var load = function (event) {
        var reader = new FileReader();
        reader.onload = function () {
            var image = document.getElementById("image");
            image.src = reader.result;
            image.style.display = "block"; // Show the image element
        }
        reader.readAsDataURL(event.target.files[0]);
    }
</script>

<style>
    .card {
        border-radius: 15px;
    }

    .form-group {
        margin-bottom: 1.5rem;
    }
</style>

Library DEPI/Views/Books/Details.cshtml
@model Library_DEPI.Models.Book

@{
    ViewData["Title"] = "Details";
}

<h1 class="text-center">Book Details</h1>

<div class="container mt-4" style="width:70%;">
    <div class="card shadow-lg p-4">
        
        <dl class="row">
            <dt class="col-sm-5">
                @Html.DisplayNameFor(model => model.Title)
            </dt>
            <dd class="col-sm-7">
                @Html.DisplayFor(model => model.Title)
            </dd>

            <dt class="col-sm-5">
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd class="col-sm-7">
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt class="col-sm-5">
                Availability Status
                @* @Html.DisplayNameFor(model => model.AvailabilityStatus) *@
            </dt>
            <dd class="col-sm-7">
                @if (Model.AvailabilityStatus)
                {
                    <span class="text-success">Available</span>
                }
                else
                {
                    <span class="text-danger">Not Available</span>
                }
            </dd>

            <dt class="col-sm-5">
                Published Date
                @* @Html.DisplayNameFor(model => model.PublishedDate) *@
            </dt>
            <dd class="col-sm-7">
                @Html.DisplayFor(model => model.PublishedDate)
            </dd>

            <dt class="col-sm-5">
                Book Image
                @* @Html.DisplayNameFor(model => model.BookImage) *@
            </dt>
            <dd class="col-sm-7">
                <img width="100" height="100" src="~/images/@Html.DisplayFor(model => model.BookImage)" alt="@Html.DisplayNameFor(model => model.Title)" />
            </dd>

            <dt class="col-sm-5">
                @Html.DisplayNameFor(model => model.Author)
            </dt>
            <dd class="col-sm-7">
                @Html.DisplayFor(model => model.Author.Name)
            </dd>

            <dt class="col-sm-5">
                @Html.DisplayNameFor(model => model.Genre)
            </dt>
            <dd class="col-sm-7">
                @Html.DisplayFor(model => model.Genre.Name)
            </dd>
        </dl>

        <div class="d-flex justify-content-between mt-4">
            @if (User.IsInRole("Admin") || User.IsInRole("Super Admin"))
            {
                <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-info btn-lg">Edit</a>
            }
            <a asp-action="Index" class="btn btn-secondary" style="font-size: 1.2rem;">Back to List</a>
        </div>
    </div>
</div>

<style>
    .text-success {
        color: green;
        font-weight: bold;
    }

    .text-danger {
        color: red;
        font-weight: bold;
    }

    .card {
        border-radius: 15px;
    }
</style>

Library DEPI/Views/Books/Index.cshtml
@* @model IEnumerable<Library_DEPI.Models.Book>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AvailabilityStatus)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PublishedDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BookImage)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Author)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genre)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @if (item.AvailabilityStatus)
                {
                    <span>Available</span>
                }
                else
                {
                    <span>Not Available</span>
                }
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.PublishedDate)
            </td>
            <td>
                
               <img height="100px" width="100px" src="~/images/@Html.DisplayFor(modelItem => item.BookImage) " alt="@Html.DisplayFor(modelItem => item.Title)" />

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Author.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genre.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>


 *@

@model IEnumerable<Library_DEPI.Models.Book>

@{
    ViewData["Title"] = "Index";
}

<h1 class="text-center">All Books</h1>
<div class="d-flex justify-content-evenly align-items-center ">


    <div>
        <form asp-action="Index" class="form-inline">
            <label>Search By</label>
             <select name="searchBy" class="form-control mr-2" style="width:200%;margin-bottom:2%;">
                <option value="Title">Title</option>
                <option value="Author">Author</option>
                <option value="Genre">Genre</option>
            </select>
            <input type="text" name="searchString" style="width:200%;" class="form-control mr-2" placeholder="Search...">
            <button type="submit" class="btn btn-secondary" style="margin-top:4%;"> Search</button>
            <button type="submit" class="btn btn-dark" asp-action="Index" style="margin-top:4%;"> Back To All Books</button>
        </form>
    </div>


    @if (User.IsInRole("Admin") || User.IsInRole("Super Admin"))
    {
        <div>
            <a asp-action="Create" class="btn btn-primary btn-lg">Create New</a>
        </div>
    }

    
</div>

@* <p>
    <a asp-action="Create">Create New</a>
</p> *@

<div class="card-container">
    @foreach (var item in Model)
    {
        <article class="card">
            <figure>
                <img src="~/images/@item.BookImage" alt="@item.Title" />
            </figure>
            <h2>@item.Title</h2>
            <p>@item.Description</p>
            <div class="details">
                <p><strong>Published:</strong> @item.PublishedDate.ToShortDateString()</p>
                <p>
                    <strong>Status:</strong> 
                    @if (item.AvailabilityStatus)
                    {
                        <span style="color:green">Available</span>
                    }
                    else
                    {
                        <span style="color:red">Not Available</span>
                    }
                </p>
            </div>
            <div class="actions">
                <p><strong>Author:</strong> @item.Author?.Name</p>
                <p><strong>Genre:</strong> @item.Genre?.Name</p>
            </div>
            <div class="action-links">
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-lg btn-secondary">Details</a>
                @if (User.IsInRole("Admin") || User.IsInRole("Super Admin"))
                {
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-lg btn-info">Edit</a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-lg btn-danger">Delete</a>

                }
                <a asp-action="Create" asp-controller="Checkout" asp-route-selectedBookId="@item.Id" class="btn btn-lg btn-warning" style="margin-top:2%;">Checkout</a>


                @* <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> *@
            </div>
        </article>
    }
</div>

<style>
    * {
        box-sizing: border-box;
    }

    .card-container {
        display: grid;
        grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
        gap: 20px;
        padding: 20px;
    }

    .card {
        background: white;
        border-radius: 15px;
        box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);
        overflow: hidden;
        transition: transform 0.3s, box-shadow 0.3s;
        padding: 15px; /* Reduced padding */
        max-height: 700px; /* Increased max height */
    }

        .card:hover {
            transform: translateY(-5px);
            box-shadow: 0 8px 30px rgba(0, 0, 0, 0.2);
        }

    figure {
        margin: 0;
        position: relative;
        height: 500px; /* Increased height for the figure */
        overflow: hidden;
    }

        figure img {
            width: 100%;
            height: auto;
            border-radius: 10px;
            max-height: 100%; /* Ensure the image fits */
            object-fit: cover; /* Cover the space */
        }

    h2 {
        font-size: 1.5em;
        margin: 10px 0;
    }

    .details, .actions {
        display: flex;
        justify-content: space-between; /* Align items */
    }

    .action-links {
        margin-top: 10px;
    }
</style>